
CREATE DATABASE cart
    DEFAULT CHARACTER SET = 'utf8mb4';

CREATE DATABASE checkout
    DEFAULT CHARACTER SET = 'utf8mb4';


CREATE DATABASE payment
    DEFAULT CHARACTER SET = 'utf8mb4';

CREATE DATABASE product
    DEFAULT CHARACTER SET = 'utf8mb4';

CREATE DATABASE user
    DEFAULT CHARACTER SET = 'utf8mb4';


CREATE DATABASE `order`
    DEFAULT CHARACTER SET = 'utf8mb4';
