version: '3'
services:
  mysql:
    image: 'mysql:latest'
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - ./db/sql/ini:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-proot"]
      interval: 20s
      timeout: 10s
      retries: 5
      start_period: 2m
  redis:
    image: 'redis:latest'
    ports:
      - 6379:6379
  consul:
    image: "hashicorp/consul:latest"
    ports:
      - "8500:8500"
    environment:
      CONSUL_BIND_INTERFACE: eth0
  # Jaeger
  jaeger-all-in-one:
    container_name: jaeger-all-in-one
    image: jaegertracing/all-in-one:latest
    ports:
      - "16686:16686"
      - "4317:4317"
      - "4318:4318"
  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./deploy/config/prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
    ports:
      - "9090:9090"
  etcd:
    image: docker.io/bitnami/etcd:latest
    environment:
      - ALLOW_NONE_AUTHENTICATION=yes
    ports:
      - 2379:2379
      - 2380:2380
  # nats
  nats:
    image: nats:latest
    ports:
      - "4222:4222"
      - "8222:8222"

  grafana:
    image: grafana/grafana:latest
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_AUTH_DISABLE_LOGIN_FORM=true
    ports:
      - "3000:3000"

  loki:
    image: grafana/loki:latest
    volumes:
      - ./deploy/config/loki.yml:/etc/loki/local-config.yaml
    command: -config.file=/etc/loki/local-config.yaml
    ports:
      - "3100:3100"

  promtail:
    image: grafana/promtail:latest
    volumes:
      - ./deploy/config/promtail.yml:/etc/promtail/config.yml
      - ./app/frontend/log:/logs/frontend
    command: -config.file=/etc/promtail/config.yml

  frontend:
    build:
      context: .
      dockerfile: ./deploy/Dockerfile.frontend
    # image: "frontend:latest"
    ports:
      - "8080:8080"
    environment:
      - SESSION_SECRET=hfbpw
      - OTEL_EXPORTER_OTLP_TRACES_ENDPOINT=jaeger-all-in-one:4317
      - OTEL_EXPORTER_OTLP_INSECURE=true
      - GO_ENV=dev
    depends_on:
      - consul
      - redis
    volumes:
      - ./app/frontend/conf/dev:/opt/gomall/frontend/conf/dev

  product:
     build:
       context: .
       dockerfile: ./deploy/Dockerfile.svc
       args:
           - SVC=product
    #  image: "product:latest"
     environment:
           - MYSQL_USER=root
           - MYSQL_PASSWORD=root
           - MYSQL_HOST=mysql
          #  - SESSION_SECRET=hfbpw
           - OTEL_EXPORTER_OTLP_TRACES_ENDPOINT=jaeger-all-in-one:4317
           - OTEL_EXPORTER_OTLP_INSECURE=true
           - GO_ENV=dev
     depends_on:
       consul:
           condition: service_started
       mysql:
           condition: service_healthy
     volumes:
       - ./app/product/conf/dev:/opt/gomall/product/conf/dev

  user:
     build:
       context: .
       dockerfile: ./deploy/Dockerfile.svc
       args:
           - SVC=user
    #  image: "user:latest"
     environment:
           - MYSQL_USER=root
           - MYSQL_PASSWORD=root
           - MYSQL_HOST=mysql
          #  - SESSION_SECRET=hfbpw
           - OTEL_EXPORTER_OTLP_TRACES_ENDPOINT=jaeger-all-in-one:4317
           - OTEL_EXPORTER_OTLP_INSECURE=true
           - GO_ENV=dev
     depends_on:
       consul:
           condition: service_started
       mysql:
           condition: service_healthy
     volumes:
       - ./app/user/conf/dev:/opt/gomall/user/conf/dev

  cart:
     build:
       context: .
       dockerfile: ./deploy/Dockerfile.svc
       args:
           - SVC=cart
    #  image: "cart:latest"
     environment:
           - MYSQL_USER=root
           - MYSQL_PASSWORD=root
           - MYSQL_HOST=mysql
          #  - SESSION_SECRET=hfbpw
           - OTEL_EXPORTER_OTLP_TRACES_ENDPOINT=jaeger-all-in-one:4317
           - OTEL_EXPORTER_OTLP_INSECURE=true
           - GO_ENV=dev
     depends_on:
       consul:
           condition: service_started
       mysql:
           condition: service_healthy
     volumes:
       - ./app/cart/conf/dev:/opt/gomall/cart/conf/dev


  checkout:
     build:
       context: .
       dockerfile: ./deploy/Dockerfile.svc
       args:
           - SVC=checkout
    #  image: "checkout:latest"
     environment:
           - MYSQL_USER=root
           - MYSQL_PASSWORD=root
           - MYSQL_HOST=mysql
          #  - SESSION_SECRET=hfbpw
           - OTEL_EXPORTER_OTLP_TRACES_ENDPOINT=jaeger-all-in-one:4317
           - OTEL_EXPORTER_OTLP_INSECURE=true
           - GO_ENV=dev
     depends_on:
       consul:
           condition: service_started
       mysql:
           condition: service_healthy
     volumes:
       - ./app/checkout/conf/dev:/opt/gomall/checkout/conf/dev


  email:
     build:
       context: .
       dockerfile: ./deploy/Dockerfile.svc
       args:
           - SVC=email
    #  image: "email:latest"
     environment:
           - MYSQL_USER=root
           - MYSQL_PASSWORD=root
           - MYSQL_HOST=mysql
          #  - SESSION_SECRET=hfbpw
           - OTEL_EXPORTER_OTLP_TRACES_ENDPOINT=jaeger-all-in-one:4317
           - OTEL_EXPORTER_OTLP_INSECURE=true
           - GO_ENV=dev
     depends_on:
       consul:
           condition: service_started
       mysql:
           condition: service_healthy
     volumes:
       - ./app/email/conf/dev:/opt/gomall/email/conf/dev


  order:
     build:
       context: .
       dockerfile: ./deploy/Dockerfile.svc
       args:
           - SVC=order
    #  image: "order:latest"
     environment:
           - MYSQL_USER=root
           - MYSQL_PASSWORD=root
           - MYSQL_HOST=mysql
          #  - SESSION_SECRET=hfbpw
           - OTEL_EXPORTER_OTLP_TRACES_ENDPOINT=jaeger-all-in-one:4317
           - OTEL_EXPORTER_OTLP_INSECURE=true
           - GO_ENV=dev
     depends_on:
       consul:
           condition: service_started
       mysql:
           condition: service_healthy
     volumes:
       - ./app/order/conf/dev:/opt/gomall/order/conf/dev

  payment:
     build:
       context: .
       dockerfile: ./deploy/Dockerfile.svc
       args:
           - SVC=payment
    #  image: "payment:latest"
     environment:
           - MYSQL_USER=root
           - MYSQL_PASSWORD=root
           - MYSQL_HOST=mysql
          #  - SESSION_SECRET=hfbpw
           - OTEL_EXPORTER_OTLP_TRACES_ENDPOINT=jaeger-all-in-one:4317
           - OTEL_EXPORTER_OTLP_INSECURE=true
           - GO_ENV=dev
     depends_on:
       consul:
           condition: service_started
       mysql:
           condition: service_healthy
     volumes:
       - ./app/payment/conf/dev:/opt/gomall/payment/conf/dev