version: '3'
services:
  consul:
    image: 'hashicorp/consul:1.20.1'
    ports:
      - 8500:8500
  mysql:
    image: "mysql:9.1.0"
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=0000
      - MYSQL_DATABASE=demo_proto
