version: '3'
services:
  consul:
    image: 'hashicorp/consul:1.20.1'
    ports:
      - 8500:8500
  mysql:
    image: "mysql:9.1.0"
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=user
    volumes:
      - ./db/sql/ini:/docker-entrypoint-initdb.d
  redis:
    image: "redis:7.4.1"
    ports:
      - 6379:6379
  nats:
    image: nats:latest
    ports:
      - "4222:4222"
      - "8222:8222"
  jaeger-all-in-one:
    image: jaegertracing/all-in-one:latest
    ports:
      - "16686:16686"
      - "4317:4317"
      - "4318:4318"
  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./deploy/config/prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
    ports:
      - "9090:9090"
  grafana:
    image: grafana/grafana:latest
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_AUTH_DISABLE_LOGIN_FORM=true
    ports:
      - "3000:3000"
