kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: gomall-dev
nodes:
  - role: control-plane
    image: kindest/node:v1.33.1
    extraMounts:
      - hostPath: ./db/sql/ini
        containerPath: /opt/gomall/db/sql/ini
      - hostPath: ./deploy/config
        containerPath: /opt/gomall/deploy/config

  - role: worker
    image: kindest/node:v1.33.1
    extraMounts:
      - hostPath: ./db/sql/ini
        containerPath: /opt/gomall/db/sql/ini
      - hostPath: ./deploy/config
        containerPath: /opt/gomall/deploy/config

  # image for China: registry.cn-hangzhou.aliyuncs.com/kindest/node:v1.33.1
  - role: worker
    image: kindest/node:v1.33.1
    extraMounts:
      - hostPath: ./db/sql/ini
        containerPath: /opt/gomall/db/sql/ini
      - hostPath: ./deploy/config
        containerPath: /opt/gomall/deploy/config
