// Code generated by hertz generator. DO NOT EDIT.

package router

import (
	"github.com/cloudwego/hertz/pkg/app/server"
	about "github.com/xilepeng/gomall/app/frontend/biz/router/about"
	auth "github.com/xilepeng/gomall/app/frontend/biz/router/auth"
	cart "github.com/xilepeng/gomall/app/frontend/biz/router/cart"
	category "github.com/xilepeng/gomall/app/frontend/biz/router/category"
	product "github.com/xilepeng/gomall/app/frontend/biz/router/product"
	// common "github.com/xilepeng/gomall/app/frontend/biz/router/common"
	home "github.com/xilepeng/gomall/app/frontend/biz/router/home"
)

// GeneratedRegister registers routers generated by IDL.
func GeneratedRegister(r *server.Hertz) {
	//INSERT_POINT: DO NOT DELETE THIS LINE!
	cart.Register(r)

	product.Register(r)

	category.Register(r)

	about.Register(r)

	auth.Register(r)

	home.Register(r)
}
